# Use postgres/example user/password credentials
version: '3.1'

services:
# https://hub.docker.com/_/postgres
# https://github.com/cookiecutter/cookiecutter-django
# https://cookiecutter-django.readthedocs.io/en/latest/developing-locally-docker.html
  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: boletin-drf
    container_name: boletin-drf
    env_file:
      - .envs/.local/.postgres
    volumes:
      - boletin-drf_postgres_data:/var/lib/postgresql/data
      - boletin-drf_data_backups:/backups
    ports:
      - 5432:5432

volumes:
  boletin-drf_postgres_data:
  boletin-drf_data_backups:


