# Generated by Django 4.1.13 on 2024-02-04 16:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_vehiculo', models.CharField(choices=[('Coche', 'Coche'), ('Ciclomotor', 'Ciclomotor'), ('Motocicleta', 'Motocicleta')], max_length=20)),
                ('Chasis', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(10)])),
                ('Modelo', models.CharField(max_length=50)),
                ('Matricula', models.CharField(max_length=7, unique=True)),
                ('Color', models.CharField(choices=[('Blanco', 'Blanco'), ('Negro', 'Negro'), ('Gris', 'Gris')], max_length=10)),
                ('Fecha_Fabricacion', models.DateTimeField()),
                ('Fecha_Matriculacion', models.DateTimeField()),
                ('Fecha_Baja', models.DateTimeField()),
                ('Suspendido', models.BooleanField()),
                ('Marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_vehiculos.marca')),
            ],
            options={
                'verbose_name_plural': 'Vehiculos',
            },
        ),
    ]
