# Generated by Django 4.1.13 on 2024-02-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_vehiculos', '0003_alter_vehiculo_fecha_baja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='Fecha_Baja',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='Suspendido',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
